

require:
  - ./polyfill.js

exit: true
growl: true
timeout: 100000


node-option:
  - 'unhandled-rejections=strict' # without leading "--", also V8 flags. Important flag. Without it mocha works unexpected

file:
  - ./test/setupDatabase.ts
